version: "3"

services:
  backend:
    image: strapi/strapi
    container_name: strapi
    environment:
      - NODE_ENV=development
      - DATABASE_CLIENT=mongo
      - DATABASE_NAME=backend
      - DATABASE_HOST=db
      - DATABASE_PORT=27017
    volumes:
      - ${PWD}:/srv/app
    ports:
      - "1337:1337"
    depends_on:
      - db

  db:
    image: mongo:4.2.12
    container_name: mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: backend
    volumes:
      - strapidata:/data/db
    ports:
      - "27017:27017"

volumes:
  strapidata:
